# The URL the site will be built for
base_url = "https://localhost"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Site theme
theme = "zola-hacker"

# The title of the site
title = "Hacker theme"

# The description of the site
description = "Hacker is a theme for Zola"

author = "John Doe"

taxonomies = [{ name = "tags" }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
title_separator = "|" # set as |, -, _, etc

# The path to the logo of the site
logo = "images/logo.png"

# Google Analytics tracking ID
google_analytics = "example-tracking-id"

# Contact form script id that points to google macros (e.g. https://script.google.com/macros/s/<script-identifier>/exec)
contact_form_script_id = "<script-identifier>"

# Visitor notifier based on IFTTT + Webhooks. Sample here - /assets/js/monitor.js
monitor = false

# Menu items
menu = [{ url = "/about", name = "About" }, { url = "/tags", name = "Tags" }]

language_code = "en-US"

# Enable OpenGraph metadata
opengraph = true

timezone = "America/New_York"
# timeformat = ""

# The path to cv file if you use cv shortcode
# cv_file = "/files/Curriculum_Vitae.pdf"

# provide link to edit page on github
edit_page = true

# Use theme specific tags page based on templates/tags.html
simplified_tags = false

# Social links
social_links = [
  { platform = "email", user_id = "johndoe@example.com" },
  { platform = "github", user_id = "johndoe" },
  { platform = "linkedin", user_id = "johndoe" },
  { platform = "feed", user_id = true },
  { platform = "keyoxide", user_id = "aspe:host:XXXXXXX" },
  # { platform = "facebook", user_id = "" },
  # { platform = "instagram", user_id = "" },
  # { platform = "pinterest", user_id = "" },
  # { platform = "twitter", user_id = "" },
  # { platform = "stackoverflow", user_id = "" },
  # { platform = "youtube", user_id = "" },
  # { platform = "telegram", user_id = "" },
]

# GitHub settings that are used to generate the edit page link
[extra.github]
username = "en9inerd"
repo = "zola-hacker"

# Giscus settings
[extra.giscus]
repo = "en9inerd/zola-hacker"
repo_id = "R_kgDOMZOW5g"
category = "Comments"
category_id = "DIC_kwDOMZOW5s4ChFNw"
mapping = "og:title"
strict = 0
reactions_enabled = 1
emit_metadata = 0
input_position = "top"
theme = "dark"
lang = "en"
loading = "lazy"
crossorigin = "anonymous"

# PGP key
[extra.pgp_key]
url = "https://keys.openpgp.org/vks/v1/by-fingerprint/0000000000000000000000000000000000000000"
fingerprint = "0000 0000 0000 0000 0000 0000 0000 0000 0000 0000"

# JSON-LD metadata
[extra.bio]
gender = "male"
employer_name = "Unknown"
employer_url = "https://unknown.com"
job_title = "Software Engineer"
links = [
  "https://github.com/johndoe",
  "https://linkedin.com/in/johndoe",
  "https://twitter.com/johndoe",
]
